name: CI - build images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'

env:
  IMAGE_NAME: hferreira/ha

jobs:
  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:amd64
            ghcr.io/${{ github.repository }}:amd64

  build-arm64:
    name: Build arm64 image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (linux/arm64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:arm64
            ${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository }}:arm64
            ghcr.io/${{ github.repository }}:latest
